typography_spectrum: 0.9413282844533978
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.33673431372915463
  lightness: 0.37261236028284717
  saturation: 0.28093664788862344
  rhythmicContrast: 0.5159036488672442
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5973886016697282
analytics:
  google: UA-13036846-2
  facebook: '1703321536657152'
  twitter: null
author:
  name: David Ryman
  email: Linux@DavidRyman.com
  url: 'https://DavidRyman.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/29c3a431-ee3a-4212-bc2e-27f3e1db4a53.png
name: DavidR Open IT
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Get Your Grid
    url: 'https://thegrid.io/#19416'
    type: external
  - name: Consulting
    url: 'http://jobs.davidryman.com'
    type: external
  - name: Showroom
    url: 'https://thegrid.ai/products'
    type: external
  - name: Dr V2
    url: 'http://v2.davidryman.com'
    type: external
  - name: MediaCenter
    id: 3de975b3-a9ba-48db-a0e4-b5ebda69e4c0
    type: content
  - name: FBP
    id: abdda614-9f65-4cf0-b1f5-c28f3852eccb
    type: content
  - name: 3D Printers
    id: f8955b02-dfa2-4962-9d88-43cca6b72cfc
    type: content
  - name: Thingiverse
    url: 'https://www.thingiverse.com/davidryman/about'
    type: external
  - name: Prints
    id: a90a5e40-993f-4efa-b5c7-d682538fb215
    type: content
  - name: Logan & Lily
    url: 'http://loganandlily.com'
    type: external
  - name: About Us
    id: d3c13538-f6dd-461f-bef2-83aeae966175
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c15a97b-3c07-41f8-9737-70ad6b87071b.jpg
title: DavidR Open it
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c03f921f-e22a-41ea-a435-df5d31e7959d.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c03f921f-e22a-41ea-a435-df5d31e7959d.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3724f77e-9219-4241-87ab-1a24b6c21285.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3724f77e-9219-4241-87ab-1a24b6c21285.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Open Philosophy Technology
purpose:
  - type: contact
    url: 'mailto:Linux@Davidryman.com'
    label: Email me
  - type: internal
    label: Deposit Funds
    item: f943fdad-e432-42b4-8693-b18b219914ad
